MODRS-4 - FOLIO-initiated sending items to the accession queue
folio-org/mod-remote-storage pull request #14
Opened 2021-01-05 08:22 UTC by khandramai

[MODRS-4](https://issues.folio.org/browse/MODRS-4) - FOLIO-initiated sending items to the accession queue

## Purpose
When Kafka subscriber receives notification message from inventory-storage, it should check the new and old attributes of the item and send item to accession if the new effective location is "marked as remote"

## Approach
Kafka message listener was introduced for inventory.items topic

### TODOS and Open Questions

1. Listener expecting instanceId field in the message
2. **How to add appropriate permissions to Listener that calling /inventory?**

## Learning
 

## Pre-Merge Checklist:
 Before merging this PR, please go through the following list and take appropriate actions.

 - Does this PR meet or exceed the expected quality standards?
   - [ ] Code coverage on new code is 80% or greater
   - [ ] Duplications on new code is 3% or less
   - [ ] There are no major code smells or security issues
 - Does this introduce breaking changes?
   - [ ] Were any API paths or methods changed, added or removed?
   - [ ] Were there any schema changes?
   - [ ] Did any of the interface versions change?
   - [ ] Were permissions changed, added, or removed?
   - [ ] Are there new interface dependencies?
   - [ ] There are no breaking changes in this PR.

 If there are breaking changes, please **STOP** and consider the following:

 - What other modules will these changes impact?
 - Do JIRAs exist to update the impacted modules?
   - [ ] If not, please create them
   - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
   - [ ] Do they have all they appropriate links to blocked/related issues?
 - Are the JIRAs under active development?
   - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
 - Do PRs exist for these changes?
   - [ ] If so, have they been approved?

 Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

 While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2021-01-05 08:56 UTC, khandramai commented
This PR can be merged only after https://issues.folio.org/browse/MODINVSTOR-649 completion.

2021-01-11 12:20 UTC, siarhei-charniak approved these changes
@khandramai, LGTM. Please take a look at inline comments and exclude `@Data`-annotated files from SonarCloud analysis to increase code coverage.

2021-01-11 12:20 UTC, siarhei-charniak commented on src/main/resources/dto/item.json
> +      "$ref": "metadata.schema",
There is an existing file `src/main/resources/swagger.api/schemas/metadata.json`. Is it possible to use it here?

2021-01-11 12:20 UTC, siarhei-charniak commented on src/main/resources/dto/item.json
> +          "$ref": "uuid.json",
There is an existing file `src/main/resources/swagger.api/schemas/uuid.json`. Is it possible to use it here?

2021-01-26 08:53 UTC, MikhailFokanov requested changes

2021-01-26 08:53 UTC, MikhailFokanov commented on src/main/java/org/folio/rs/domain/dto/DomainEventType.java
> +public enum DomainEventType {
There is another type of event. If you don't declare it here, there will be an exception

2021-01-26 08:53 UTC, merged

2021-01-26 09:36 UTC, MikhailFokanov commented on src/main/java/org/folio/rs/client/EnrichHeadersClient.java
> +public class EnrichHeadersClient extends Client.Default {
This will be removed in the next PRs, as there is an alternative in spring-folio